# this file expose the endpoints

from django.urls import path, include # standard django URL routing utilities. 'path' defines specific URL strings and 'include' pulls in a set of sub-urls from elsewhere 

from rest_framework.routers import DefaultRouter # a DRF tool that auto builds all the standard CRUD URL patterns for a viewset

from .views import ChatViewSet

router = DefaultRouter()
router.register(r'', ChatViewSet) # register ViewSet with the router at the root path
# since, DefaultRouter is being used
# DRF will auto generate
# GET / - list all chats
# POST / - create a new chat
# GET /<id>/ - view a specific chat
# PUT /<id>/ - update a specific chat
# DELETE /<id>/ - delete a specific chat


urlpatterns = [
    path('chat/', include(router.urls)), # tracks the prefix /chat/ onto all the routes generated by the router
]