"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_FILE = Path(os.getenv('LOG_FILE', BASE_DIR / 'logs' / 'backend.log'))
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

load_dotenv(BASE_DIR.parent / ".env") # find .env in the parent directory
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY') # fetching OPENAI_API_KEY from the .env

WEBHOOK_TRIGGER_URL = os.getenv('WEBHOOK_TRIGGER_URL')
N8N_CANCEL_WEBHOOK_URL = os.getenv('N8N_CANCEL_WEBHOOK_URL')
N8N_CRM_WEBHOOK_URL = os.getenv('N8N_CRM_WEBHOOK_URL')
N8N_HEALTH_URL = os.getenv('N8N_HEALTH_URL', 'http://n8n:5678/healthz')
N8N_WEBHOOK_SECRET = os.getenv(
    'N8N_WEBHOOK_SECRET',
    'development-n8n-secret' if DEBUG else '',
)
N8N_HEALTH_TIMEOUT_SECONDS = float(os.getenv('N8N_HEALTH_TIMEOUT_SECONDS', '3'))
AUTOMATION_WORKER_STALE_SECONDS = int(os.getenv('AUTOMATION_WORKER_STALE_SECONDS', '30'))


WHATSAPP_ACCESS_TOKEN=os.getenv('WHATSAPP_ACCESS_TOKEN')
WHATSAPP_PHONE_NUMBER_ID=os.getenv('WHATSAPP_PHONE_NUMBER_ID')
WHATSAPP_BASE_ENDPOINT=os.getenv('WHATSAPP_BASE_ENDPOINT')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'unsafe-development-only-key'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG=False.')

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ADMIN_URL = os.getenv('ADMIN_URL', 'admin/').strip('/') + '/'

CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

CORS_ALLOW_HEADERS = (*default_headers, 'idempotency-key')
CORS_EXPOSE_HEADERS = ['X-Request-ID']

# Application definition

INSTALLED_APPS = [ # registers all the active components of the project
    'rest_framework', # DRF package registration to build the endpoints
    'rest_framework.authtoken', # token authentication for protected API routes
    'drf_spectacular', # generates the OpenAPI schema and Swagger documentation
    'leads.apps.LeadsConfig', # links to 'leads' app configuration
    'chat.apps.ChatConfig', # links to 'chat' app configuration
    'appointment.apps.AppointmentConfig', # links to 'appointment' app configuration
    'automation.apps.AutomationConfig',  # links to 'automation' app configuration
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [ # a pipeline of security and session handlers that process every request and response
    'corsheaders.middleware.CorsMiddleware',
    'mysite.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls' # tells django to start its API route parsing from the main project folder's urls.py file

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('API_ANON_RATE', '60/min'),
        'user': os.getenv('API_USER_RATE', '300/min'),
        'chat': os.getenv('API_CHAT_RATE', '20/min'),
        'auth': os.getenv('API_AUTH_RATE', '10/min'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AI Voice Agent API',
    'DESCRIPTION': 'API for conversations, leads, appointments, and booking automation.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/' 

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {'()': 'mysite.observability.JsonFormatter'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        'rotating_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_FILE),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'loggers': {
        'app': {
            'handlers': ['console', 'rotating_file'],
            'level': os.getenv('APP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
