# Generated by Django 6.0.5 on 2026-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending'), ('F', 'Failed')], default='M', max_length=1),
        ),
    ]
