# Generated by Django 6.0.5 on 2026-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=12)),
                ('service_needed', models.CharField(choices=[('DC', 'Dental Checkup'), ('TC', 'Teeth Cleaning'), ('TP', 'Tooth Pain'), ('WH', 'Whitening'), ('BC', 'Braces Consultation'), ('RC', 'Root Canal'), ('TF', 'Tooth Filling')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
