# Generated by Django 6.0.5 on 2026-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_chat_rename_formdate_formdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=12)),
                ('service_needed', models.CharField(choices=[('DC', 'Dental Checkup'), ('TC', 'Teeth Cleaning'), ('TP', 'Tooth Pain'), ('WH', 'Whitening'), ('BC', 'Braces Consultation'), ('RC', 'Root Canal'), ('TF', 'Tooth Filling')])),
                ('urgency', models.CharField(choices=[('S', 'Severe'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')])),
                ('lead_score', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pending'), ('F', 'Failed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
