# Generated by Django 6.0.5 on 2026-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_delete_chat_delete_formdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_score',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='urgency',
        ),
        migrations.AlterField(
            model_name='lead',
            name='service_needed',
            field=models.CharField(choices=[('DENTAL CHECKUP', 'Dental Health Exam and Checkup'), ('TEETH CLEANING', 'Teeth Cleanings'), ('MOUTH GUARD', 'Custom Fitted Guards for sports or prevent grinding (bruxism)'), ('WHITENING', 'Whitening and remove stains'), ('DENTAL FILLING', 'Repair Cavities'), ('RCT', 'Root Canal Treatment'), ('DENTURES', 'Dentures to replace missing teeth (complete or partial)')], max_length=25),
        ),
    ]
